name: Sync to Public Repository

on:
  push:
    branches:
      - main  # This job will run when commits are pushed to the main branch.

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Configure Git
      run: |
        git config --global user.email "1varunvc@gmail.com"
        git config --global user.name "Varun Chawla"

    - name: Remove Private Files
      run: |
        rm -f messages.js  # Ensure the path is correct if messages.js is not in the root
        rm -rf .github

    - name: Push to Public Repository
      run: |
        git remote add public https://${{ secrets.INTERNAL_PAT }}@github.com/1varunvc/schedule-personalised-sms.git
        git fetch public
        git push public main --force
