name: Manual Push Test

on: 
  push:
    branches:
      - main

jobs:
  test-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v2

    - name: Configure Git
      run: |
        git config --global user.email "1varunvc@gmail.com"
        git config --global user.name "Varun Chawla"

    - name: Make a trivial change
      run: echo "Last updated at $(date)" >> TIMESTAMP.txt

    - name: Commit and push
      run: |
        git add TIMESTAMP.txt
        git commit -m "Update TIMESTAMP"
        git push https://github.com/1varunvc/schedule-personalised-sms.git
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        FIRST_NAME: Mona
        LAST_NAME: Octocat
